import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import { openAuthModal, setAuthFromGoogle } from '../store/authSlice'
import { toast } from '../store/uiSlice'

const FEATURES = [
  { icon: '🧠', title: 'AI-Powered Content',  desc: 'Every slide, quiz, and module generated by advanced LLMs calibrated to your exact topic and level.' },
  { icon: '📹', title: 'Curated Videos',       desc: 'Each module surfaces the best YouTube resources, scored and ranked for relevance.' },
  { icon: '📐', title: 'LaTeX Math',           desc: 'First-class MathJax rendering — perfect for STEM courses at any difficulty.' },
  { icon: '📚', title: 'Validated References', desc: 'Every module comes with scored reference links so you can always go deeper.' },
  { icon: '⚡', title: 'Under 3 Minutes',      desc: 'Full multi-module courses generated in minutes with real-time streaming progress.' },
  { icon: '🎯', title: '5 Skill Levels',       desc: 'Beginner to Expert — the AI calibrates depth, vocabulary, and pacing for you.' },
]

const Logo = () => (
  <div className="flex items-center gap-2.5">
    <div className="w-8 h-8 rounded-lg bg-accent flex items-center justify-center text-white font-bold text-sm">✦</div>
    <span className="font-display text-[18px] font-bold text-white">StudyGuru <span className="text-accent">AI</span></span>
  </div>
)

const Btn = ({ onClick, children, variant = 'primary', className = '' }) => {
  const base = 'inline-flex items-center justify-center gap-2 px-6 py-3 rounded-lg font-semibold text-[14px] transition-all duration-150'
  const vars = {
    primary: 'bg-accent text-white hover:bg-accent2 shadow-glow',
    outline: 'border border-navy-400/60 text-navy-200 hover:border-accent hover:text-white',
  }
  return <button onClick={onClick} className={`${base} ${vars[variant]} ${className}`}>{children}</button>
}

export default function Landing() {
  const dispatch = useDispatch()
  const navigate = useNavigate()
  const { isAuthenticated, role: _role } = useSelector((s) => s.auth)

  useEffect(() => {
    const p = new URLSearchParams(window.location.search)
    const accessToken  = p.get('token') || p.get('access_token')
    const refreshToken = p.get('refresh_token')
    const userB64      = p.get('user')
    if (accessToken && userB64) {
      try {
        const user = JSON.parse(atob(userB64))
        dispatch(setAuthFromGoogle({ access_token: accessToken, refresh_token: refreshToken, user }))
        dispatch(toast('Signed in with Google! 🎉'))
        window.history.replaceState({}, '', '/')
        navigate(user.role === 'admin' ? '/dashboard' : '/student')
      } catch (_) {
        dispatch(toast('Google sign-in failed — please try again.'))
        window.history.replaceState({}, '', '/')
      }
    }
  }, [dispatch, navigate])

  const { role } = useSelector((s) => s.auth)

  useEffect(() => {
    if (isAuthenticated) {
      navigate(role === 'admin' ? '/dashboard' : '/student')
    }
  }, [isAuthenticated, role, navigate])

  return (
    <div className="min-h-screen hero-bg dot-grid">
      {/* nav */}
      <nav className="sticky top-0 z-50 border-b border-navy-600/60 backdrop-blur-xl bg-navy-800/80">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Logo />
          <div className="flex items-center gap-2">
            <Btn variant="outline" onClick={() => dispatch(openAuthModal('login'))}>Log In</Btn>
            <Btn variant="primary" onClick={() => dispatch(openAuthModal('signup'))}>Sign Up Free</Btn>
          </div>
        </div>
      </nav>

      {/* hero */}
      <section className="max-w-6xl mx-auto px-6 pt-24 pb-16 text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent/10 border border-accent/20 text-accent text-[12px] font-semibold mb-8">
          <span className="w-1.5 h-1.5 rounded-full bg-accent" style={{ animation: 'pulseDot 2s ease-in-out infinite' }} />
          AI-Powered Learning Platform
        </div>
        <h1 className="font-display text-[58px] font-bold leading-[1.1] text-white mb-5 animate-slide-up">
          Study Smarter.<br />
          <span className="text-accent">Learn Anything.</span>
        </h1>
        <p className="text-navy-300 text-[17px] max-w-xl mx-auto mb-10 leading-relaxed animate-slide-up" style={{ animationDelay:'60ms' }}>
          Paste any syllabus. Get a fully structured, slide-by-slide course — with curated videos, LaTeX math, and validated references.
        </p>
        <div className="flex items-center justify-center gap-3 animate-slide-up" style={{ animationDelay:'120ms' }}>
          <Btn variant="primary" className="px-8 py-3.5 text-[15px]" onClick={() => dispatch(openAuthModal('signup'))}>
            Get Started Free →
          </Btn>
          <Btn variant="outline" className="px-8 py-3.5 text-[15px]" onClick={() => dispatch(openAuthModal('login'))}>
            Log In
          </Btn>
        </div>

        {/* terminal mockup */}
        <div className="mt-16 max-w-3xl mx-auto animate-slide-up" style={{ animationDelay:'200ms' }}>
          <div className="rounded-xl border border-navy-600/60 bg-navy-900/90 overflow-hidden shadow-modal">
            <div className="flex items-center gap-2 px-5 py-3 border-b border-navy-700/60 bg-navy-800/60">
              <span className="w-3 h-3 rounded-full bg-danger/60" />
              <span className="w-3 h-3 rounded-full bg-warn/60" />
              <span className="w-3 h-3 rounded-full bg-success/60" />
              <span className="ml-4 text-[12px] text-navy-400 font-mono">Generating: Quantum Computing Fundamentals</span>
            </div>
            <div className="p-5 font-mono text-[12px] space-y-1.5 text-left">
              {[
                { c:'text-navy-400', m:'📋 Building outline — 4 modules, 18 submodules' },
                { c:'text-success',  m:'✅ Outline validated' },
                { c:'text-accent',   m:'🧠 Generating Module 1: Qubits & Superposition…' },
                { c:'text-navy-300', m:'   ✍  Slide 1/5: What is a Qubit?' },
                { c:'text-navy-300', m:'   ✍  Slide 2/5: The Bloch Sphere' },
                { c:'text-success',  m:'✅ Module 1 done — 5 YouTube videos curated' },
                { c:'text-accent',   m:'🧠 Generating Module 2: Quantum Entanglement…' },
              ].map((l, i) => <div key={i} className={l.c}>{l.m}</div>)}
              <div className="flex items-center gap-2 text-navy-500 mt-1">
                <span className="w-3 h-3 border-2 border-navy-500 border-t-accent rounded-full animate-spin-slow flex-shrink-0" />
                <span>Processing…</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* stats */}
      <section className="max-w-6xl mx-auto px-6 py-10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 stagger">
          {[['10K+','Courses Generated'],['98%','Satisfaction Rate'],['<3 min','Avg. Generation'],['150+','Subject Domains']].map(([n,l]) => (
            <div key={l} className="rounded-lg border border-navy-600/50 bg-navy-700/40 p-5 text-center">
              <div className="font-display text-[32px] font-bold text-accent leading-none mb-1.5">{n}</div>
              <div className="text-[12px] text-navy-300">{l}</div>
            </div>
          ))}
        </div>
      </section>

      {/* features */}
      <section className="max-w-6xl mx-auto px-6 py-14">
        <h2 className="font-display text-[34px] font-bold text-white text-center mb-3">Everything you need</h2>
        <p className="text-navy-300 text-[15px] text-center mb-10 max-w-lg mx-auto">StudyGuru AI handles content creation — you focus on learning.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 stagger">
          {FEATURES.map((f) => (
            <div key={f.title} className="rounded-lg border border-navy-600/40 bg-navy-700/30 p-6 hover:border-accent/40 hover:bg-navy-700/60 transition-all group">
              <h3 className="font-semibold text-white text-[15px] mb-1.5 group-hover:text-accent transition-colors">{f.title}</h3>
              <p className="text-navy-300 text-[13px] leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* cta */}
      <section className="max-w-6xl mx-auto px-6 py-16">
        <div className="rounded-xl border border-accent/20 bg-navy-700/50 p-14 text-center">
          <h2 className="font-display text-[32px] font-bold text-white mb-3">Ready to start learning?</h2>
          <p className="text-navy-300 mb-7 text-[15px]">Join thousands of learners building knowledge with AI-generated courses.</p>
          <Btn variant="primary" className="px-10 py-3.5 text-[15px]" onClick={() => dispatch(openAuthModal('signup'))}>
            Create Your First Course →
          </Btn>
        </div>
      </section>

      {/* footer */}
      <footer className="border-t border-navy-700/60 py-7">
        <div className="max-w-6xl mx-auto px-6 flex items-center justify-between">
          <Logo />
          <p className="text-navy-500 text-[12px]">© 2025 StudyGuru AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
